---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-roxs-app
resources:
  - namespace.yaml
  - my-roxs-app-deployment.yaml
  - my-roxs-app-service.yaml
  - my-roxs-app-hpa.yaml