---
apiVersion: v1
kind: Service
metadata:
  name: my-roxs-app-service
  namespace: my-roxs-app
  labels:
    app: my-roxs-app
    version: 0.0.1
    backstage.io/kubernetes-id: my-roxs-app
spec:
  type: ClusterIP
  ports:
  - name: tcp-node
    port: 8080
  selector:
    app: my-roxs-app