---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-roxs-app
  namespace: my-roxs-app
  labels:
    app: my-roxs-app
    version: 0.0.1
    backstage.io/kubernetes-id: my-roxs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-roxs-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-roxs-app
        version: 0.0.1
        backstage.io/kubernetes-id: my-roxs-app     
    spec:
      containers:
      - name: my-roxs-app
        image: webgo
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /health-check/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /health-check/liveness
          initialDelaySeconds: 3
          periodSeconds: 15