---
apiVersion: v1
kind: Namespace
metadata:
  name: my-roxs-app
  labels:
    kubernetes.io/metadata.name: my-roxs-app
    backstage.io/kubernetes-id: my-roxs-app
    istio-injection: enabled
spec:
  finalizers:
  - kubernetes