apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prueba-go-finish-hpa
  namespace: prueba-go-finish
  labels:
    app: prueba-go-finish
    version: 0.0.1
    backstage.io/kubernetes-id: prueba-go-finish
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: prueba-go-finish
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75