---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prueba-aws-eks
resources:
  - namespace.yaml
  - prueba-aws-eks-deployment.yaml
  - prueba-aws-eks-service.yaml
  - prueba-aws-eks-hpa.yaml