apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prueba-aws-eks-hpa
  namespace: prueba-aws-eks
  labels:
    app: prueba-aws-eks
    version: 0.0.1
    backstage.io/kubernetes-id: prueba-aws-eks
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: prueba-aws-eks
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75