---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prueba-go-argo
resources:
  - namespace.yaml
  - prueba-go-argo-deployment.yaml
  - prueba-go-argo-service.yaml
  - prueba-go-argo-hpa.yaml