---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-go-argo
  namespace: prueba-go-argo
  labels:
    app: prueba-go-argo
    version: 0.0.1
    backstage.io/kubernetes-id: prueba-go-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prueba-go-argo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prueba-go-argo
        version: 0.0.1
        backstage.io/kubernetes-id: prueba-go-argo  
    spec:
      containers:
      - name: prueba-go-argo
        image: webgo
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /health-check/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /health-check/liveness
          initialDelaySeconds: 3
          periodSeconds: 15