---
apiVersion: v1
kind: Service
metadata:
  name: prueba-golang-service
  namespace: prueba-golang
  labels:
    app: prueba-golang
    version: 0.0.1
    backstage.io/kubernetes-id: prueba-golang
spec:
  type: ClusterIP
  ports:
  - name: tcp-node
    port: 8080
  selector:
    app: prueba-golang